### ISSUE TITLE
how can i use virtual box with this efi

### ISSUE THREAD

**Issue by bluesiboy** [ExodazTH/RyzenHackintosh#1]
i can't found '**vmx**' on command `sysctl -a | grep machdep.cpu.features`.
and  result is 0 on command `sysctl kern.hv_support` .
and when i create virtual machine and start it, then throw  exception :  **The virtual machine 'Master' has terminated unexpectedly during startup with exit code 1 (0x1)** 。

**Comment by ExodazTH** [comment]
Try Enable 4G Decoding on BIOS

**Comment by bluesiboy** [comment]
> Try Enable 4G Decoding on BIOS

yes, i found `Above 4G Descoding` on BIOS and enable it,  but still can't open vmbox.
