### ISSUE TITLE
This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory

### ISSUE THREAD

**Issue by bluesiboy** [ExodazTH/RyzenHackintosh#2]
Command failed: /usr/local/bin/docker-machine -D create -d virtualbox --virtualbox-memory 2048 default,Docker Machine Version: 0.16.1, build cce350d7,Found binary path at /usr/local/bin/docker-machine,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:50113,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(flag-lookup) Calling .GetMachineName,(flag-lookup) Calling .DriverName,(flag-lookup) Calling .GetCreateFlags,Found binary path at /usr/local/bin/docker-machine,Launching plugin server for driver virtualbox,Plugin server listening at address 127.0.0.1:50119,() Calling .GetVersion,Using API Version 1,() Calling .SetConfigRaw,() Calling .GetMachineName,(default) Calling .GetMachineName,(default) Calling .DriverName,(default) Calling .GetCreateFlags,(default) Calling .SetConfigFromFlags,Reading certificate data from /Users/blueboy/.docker/machine/certs/ca.pem,Decoding PEM data...,Parsing certificate...,Reading certificate data from /Users/blueboy/.docker/machine/certs/cert.pem,Decoding PEM data...,Parsing certificate...,(default) Calling .PreCreateCheck,(default) DBG | COMMAND: /usr/local/bin/VBoxManage --version,(default) DBG | STDOUT:,(default) DBG | {,(default) DBG | 6.1.16r140961,(default) DBG | },(default) DBG | STDERR:,(default) DBG | {,(default) DBG | },Error with pre-create check: "This computer doesn't have VT-X/AMD-v enabled. Enabling it in the BIOS is mandatory",Opting out of crash reporting.,

**Comment by ExodazTH** [comment]
Enable 4G Decoding ?

**Comment by bluesiboy** [comment]
> Enable 4G Decoding ?

Big Sur  + AMD R7 3800x + B450M + RX 580 
my  machine dos'nt have  Virtualization features 。
1. 【sysctl -a | grep machdep.cpu.features】  do not have `VMX`
2. 【sysctl kern.hv_support】 result is `0`  not 1。

but when my machine os is `Catalina` ， vmbox can be running ， not have errors。
i try get new CPU Fix PATH to replace config.plist with https://github.com/AMD-OSX/AMD_Vanilla/tree/opencore/17h_19h， there are still errors.

**Comment by bluesiboy** [comment]
> Enable 4G Decoding ?

yes, i found `Above 4G Descoding` on BIOS and enable it, but still can't open vmbox.

**Comment by ExodazTH** [comment]
> 
> 
> > Enable 4G Decoding ?
> 
> yes, i found `Above 4G Descoding` on BIOS and enable it, but still can't open vmbox.

no idea
